export enum ValidRutines {
  GYM = 'GYM',
  CARDIO = 'CARDIO',
  CROSSFIT = 'CROSSFIT',
  FUNCTIONAL = 'FUNCTIONAL',
  PILATES = 'PILATES',
  YOGA = 'YOGA',
  SWIMMING = 'SWIMMING',
  RUNNING = 'RUNNING',
  CYCLING = 'CYCLING',
  CLIMBING = 'CLIMBING',
  SKATEBOARD = 'SKATEBOARD',
  CALISTENIA = 'CALISTENIA',
}
